version: "3.9"

services:
  InventAPI:
    container_name: InventAPI
    image: inventory:1
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://user:password@InventAPI_db:5432/postgres
    depends_on:
    - InventAPI_db
    - InventAPI_cache
  
  InventAPI_db:
    container_name: InventAPI_db
    image: postgres:latest
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres 
    volumes:
        - pgdata:/var/lib/postgresql/data

  InventAPI_cache:
    image: redis:latest
    container_name: InventAPI_cache
    ports:
     - "6379:6379"
volumes:
  pgdata: {}